# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-07 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='component',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField(auto_now=True)),
                ('board', models.CharField(max_length=30)),
                ('part_num', models.PositiveIntegerField()),
                ('serial_num', models.PositiveIntegerField()),
                ('handling', models.CharField(choices=[('R', 'RMA'), ('P', 'Production')], max_length=1)),
                ('notes', models.CharField(blank=True, max_length=100)),
                ('user_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='fixed_board',
            fields=[
                ('entry_date', models.DateField(auto_now=True)),
                ('board', models.CharField(max_length=30)),
                ('serial_num', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('handling', models.CharField(choices=[('R', 'RMA'), ('P', 'Production'), ('E', 'Engineering')], max_length=1)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('user_name', models.CharField(max_length=30)),
            ],
        ),
    ]
