# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-25 19:15
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='component',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField(auto_now=True)),
                ('board', models.CharField(max_length=30)),
                ('part_num', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^.{8,}$', 'Must be at least 8 characters')])),
                ('serial_num', models.PositiveIntegerField(validators=[django.core.validators.RegexValidator('^\\d{8}$', 'Must be 8 digit Serial Number', 'Invalid Number')])),
                ('handling', models.CharField(choices=[('RMA', 'RMA'), ('Production', 'Production')], max_length=10)),
                ('notes', models.CharField(blank=True, max_length=100)),
                ('user_name', models.CharField(max_length=30)),
                ('ref_des', models.CharField(max_length=150)),
                ('bag_id', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='fixed_board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField(auto_now=True)),
                ('board', models.CharField(max_length=30)),
                ('serial_num', models.PositiveIntegerField(validators=[django.core.validators.RegexValidator('^\\d{8}$', 'Must be 8 digit Serial Number', 'Invalid Number')])),
                ('handling', models.CharField(choices=[('RMA', 'RMA'), ('Production', 'Production'), ('Engineering', 'Engineering')], max_length=11)),
                ('notes', models.TextField()),
                ('user_name', models.CharField(max_length=30)),
            ],
        ),
    ]
