# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-18 14:41
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('removed', '0002_auto_20170718_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixed_board',
            name='serial_num',
            field=models.PositiveIntegerField(validators=[django.core.validators.RegexValidator('\\d{8,8}', 'Must be 8 digit Serial Number', 'Invalid Number')]),
        ),
    ]
