# Generated by Django 2.0.1 on 2018-01-11 10:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='boardgame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cover', models.ImageField(help_text='Image size limit = 100kb', upload_to='')),
                ('p_min', models.PositiveSmallIntegerField(null=True)),
                ('p_max', models.PositiveSmallIntegerField(blank=True, help_text='Optional', null=True)),
                ('age', models.PositiveSmallIntegerField(null=True)),
                ('time', models.PositiveSmallIntegerField(help_text='Estimated time per game \n in minutes', null=True)),
                ('play_style', models.CharField(choices=[('cp', 'Cooperation'), ('tm', 'Team vs. Team'), ('ev', 'Competitive')], max_length=2)),
                ('game_genre', models.CharField(choices=[('cd', 'Card Game'), ('bd', 'Board Game')], max_length=2)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
