# Generated by Django 2.0.1 on 2018-01-05 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='playerChar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race', models.CharField(max_length=50)),
                ('charclass', models.CharField(max_length=100)),
                ('level', models.PositiveSmallIntegerField(null=True)),
                ('name', models.CharField(max_length=100)),
                ('exp', models.PositiveIntegerField(blank=True, null=True)),
                ('gold', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('strength', models.PositiveSmallIntegerField(null=True)),
                ('dex', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('const', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('intel', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('wis', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('char', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('prof_bonus', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('inspiration', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('max_hitpoints', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('cur_hitpoints', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('ac', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('initiative', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('speed', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('skills', multiselectfield.db.fields.MultiSelectField(choices=[('acr', 'Acrobatics'), ('anm', 'Animal Handling'), ('arc', 'Arcana'), ('ath', 'Athletics'), ('dec', 'Deception'), ('his', 'History'), ('ins', 'Insight'), ('int', 'Intimidation'), ('inv', 'Investigation'), ('med', 'Medicine'), ('nat', 'Nature'), ('per', 'Perception'), ('pfm', 'Performance'), ('psn', 'Persuasion'), ('rel', 'Religion'), ('soh', 'Slight of Hand'), ('sth', 'Stealth'), ('sur', 'Survival')], max_length=71)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
